version: 2
jobs:
  info:
    docker:
      - image: circleci/node:8.9
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn $(yarn --version)"
  setup:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
      - restore_cache:
          key: dependency-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn/
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run:
          name: Test
          command: CI=true yarn test
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run:
          name: Build
          command: CI=true yarn run build
      - store_artifacts:
          path: ./build
      - save_cache:
          key: build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project/build
  deploy:
    machine:
      enabled: true
    steps:
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy
          command: echo "Replace with deploy command"
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - info
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build